---
env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - airbnb
  - airbnb/hooks
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
  - react
  - json
  - jest
rules:
  prettier/prettier: error
  arrow-parens: 0
  no-warning-comments: error
  import/prefer-default-export: 0
  import/no-extraneous-dependencies:
    ['error', { devDependencies: ['.storybook/**', 'stories/**'] }]
settings:
  import/extensions:
    - .js
    - .jsx
